#	Which Kubernetes API version to use (for Deployments, use apps/v1)
apiVersion: apps/v1
kind: Deployment
metadata:
#Deployments name
  name: test-deployment
  # separate different projects inside the same cluster
  namespace: playground1
spec:
  replicas: 3
  selector:
    matchLabels:
#selector: matchLabels: app: test . These Pods belong to this Deployment"
      app: test
#	The blueprint for each Pod
  template:
    metadata:
#	A sticker on each Pod so the selector can find it
      labels:
        app: test
    spec:
#	The list of containers inside the Pod
      containers:
        - name: test-container
#	Which Docker image to use for this container
          image: sultanss/test:v1
          ports:
            - containerPort: 3000