apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: pds   # samma namespace som din deployment
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: testtesttesttesettesetteset