apiVersion: v1
kind: Secret
metadata:
  name: my-nextjs-secret
  namespace: playground1
type: Opaque
data:
  # Alla värden måste vara base64-kodade!
  # Så här skapas base64 av "mitt-riktiga-values":
  #   echo -n "mitt-riktiga-lösenord" | base64
  username: dGVzdC11c2Vy
  password: dGVzdC1wYXNzd29yZA==
  DATABASE_PASSWORD: bXlwYXNzd29yZAfake==   # "mypassword" i base64
  API_PRIVATE_KEY: bXlwcml2YXRla2V5fake     # "myprivatekey" i base64
  API_PUBLIC_KEY: bXlwdWJsaWNrZXkfake=      # "mypublickey" i base64

  